"""add_phone_number_to_users

Revision ID: 479c7e35fb4e
Revises: e377efb9dcce
Create Date: 2023-02-13 22:06:34.292481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479c7e35fb4e'
down_revision = 'e377efb9dcce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
