"""modify_user_table

Revision ID: e377efb9dcce
Revises: f11787a9d406
Create Date: 2023-02-13 22:01:08.558917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e377efb9dcce'
down_revision = 'f11787a9d406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(), server_default='User_<function uuid4 at 0x7fb1e0705d80>', nullable=False))
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('surname', sa.String(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_otp_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['login'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_otp_key', 'users', ['otp'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'surname')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
