"""fix_login_in_users

Revision ID: 014d53ed6b4c
Revises: d36ff2651ed7
Create Date: 2023-02-13 22:45:42.857812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014d53ed6b4c'
down_revision = 'd36ff2651ed7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'User_<function uuid4 at 0x7fb1e0705d80>'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
