"""fix_login_in_users

Revision ID: d36ff2651ed7
Revises: 3d675ef66460
Create Date: 2023-02-13 22:29:38.023647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36ff2651ed7'
down_revision = '3d675ef66460'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
